# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import air_craft_pb2 as air__craft__pb2


class ShipsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAircraft = channel.unary_stream(
            "/protoships.ShipsService/GetAircraft",
            request_serializer=air__craft__pb2.RequestSpaceCoor.SerializeToString,
            response_deserializer=air__craft__pb2.ResponceAircraft.FromString,
        )


class ShipsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAircraft(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ShipsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetAircraft": grpc.unary_stream_rpc_method_handler(
            servicer.GetAircraft,
            request_deserializer=air__craft__pb2.RequestSpaceCoor.FromString,
            response_serializer=air__craft__pb2.ResponceAircraft.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "protoships.ShipsService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class ShipsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAircraft(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_stream(
            request,
            target,
            "/protoships.ShipsService/GetAircraft",
            air__craft__pb2.RequestSpaceCoor.SerializeToString,
            air__craft__pb2.ResponceAircraft.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
